# This file is automatically generated, you probably don't want to edit this

LearnTTestOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnTTestOptions',
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            testType = 'independent',
            dep = NULL,
            group = NULL,
            dep2 = NULL,
            mu = 0,
            hypothesis = 'twoTailed',
            showTheory = TRUE,
            showInstructions = TRUE,
            ...) {

            super$initialize(
                package = 'learnJamovi',
                name = 'LearnTTest',
                requiresData = TRUE,
                ...)

            private$..testType <- jmvcore::OptionList$new(
                'testType', testType,
                options = list('independent', 'paired', 'onesample'))

            private$..dep <- jmvcore::OptionVariable$new(
                'dep', dep,
                suggested = list('continuous'),
                permitted = list('numeric'))

            private$..group <- jmvcore::OptionVariable$new(
                'group', group,
                suggested = list('nominal', 'ordinal'),
                permitted = list('factor'))

            private$..dep2 <- jmvcore::OptionVariable$new(
                'dep2', dep2,
                suggested = list('continuous'),
                permitted = list('numeric'))

            private$..mu <- jmvcore::OptionNumber$new(
                'mu', mu)

            private$..hypothesis <- jmvcore::OptionList$new(
                'hypothesis', hypothesis,
                options = list('twoTailed', 'oneGreater', 'oneLess'))

            private$..showTheory <- jmvcore::OptionBool$new(
                'showTheory', showTheory)

            private$..showInstructions <- jmvcore::OptionBool$new(
                'showInstructions', showInstructions)

            self$.addOption(private$..testType)
            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..dep2)
            self$.addOption(private$..mu)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..showTheory)
            self$.addOption(private$..showInstructions)
        }),
    active = list(
        testType         = function() private$..testType$value,
        dep              = function() private$..dep$value,
        group            = function() private$..group$value,
        dep2             = function() private$..dep2$value,
        mu               = function() private$..mu$value,
        hypothesis       = function() private$..hypothesis$value,
        showTheory       = function() private$..showTheory$value,
        showInstructions = function() private$..showInstructions$value),
    private = list(
        ..testType         = NA,
        ..dep              = NA,
        ..group            = NA,
        ..dep2             = NA,
        ..mu               = NA,
        ..hypothesis       = NA,
        ..showTheory       = NA,
        ..showInstructions = NA))

LearnTTestResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnTTestResults',
    inherit = jmvcore::Group,
    active = list(
        theory       = function() private$.items[['theory']],
        instructions = function() private$.items[['instructions']],
        ttest        = function() private$.items[['ttest']],
        desc         = function() private$.items[['desc']]),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name = '',
                title = 'T-Tests')

            self$add(jmvcore::Html$new(
                options = options,
                name = 'theory',
                title = 'Statistical Theory',
                visible = '(showTheory)',
                clearWith = list()))

            self$add(jmvcore::Html$new(
                options = options,
                name = 'instructions',
                title = 'Jamovi Instructions',
                visible = '(showInstructions)',
                clearWith = list()))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'ttest',
                title = 'T-Test Results',
                clearWith = list('dep', 'group', 'dep2', 'mu', 'hypothesis', 'testType'),
                columns = list(
                    list(name = 'var',     title = '',           type = 'text'),
                    list(name = 't',       title = 't',          type = 'number'),
                    list(name = 'df',      title = 'df',         type = 'number'),
                    list(name = 'p',       title = 'p',          type = 'number', format = 'zto,pvalue'),
                    list(name = 'md',      title = 'Mean diff.', type = 'number'),
                    list(name = 'cilower', title = 'Lower',      type = 'number', superTitle = '95% CI'),
                    list(name = 'ciupper', title = 'Upper',      type = 'number', superTitle = '95% CI'),
                    list(name = 'cohend',  title = "Cohen's d",  type = 'number'))))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'desc',
                title = 'Group Descriptives',
                clearWith = list('dep', 'group', 'dep2', 'testType'),
                columns = list(
                    list(name = 'group', title = 'Group', type = 'text'),
                    list(name = 'n',     title = 'N',     type = 'integer'),
                    list(name = 'mean',  title = 'Mean',  type = 'number'),
                    list(name = 'sd',    title = 'SD',    type = 'number'),
                    list(name = 'se',    title = 'SE',    type = 'number'))))
        }))

LearnTTestBase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnTTestBase',
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = '', analysisId = '', revision = 0) {
            super$initialize(
                package = 'learnJamovi',
                name = 'LearnTTest',
                version = c(1, 0, 0),
                options = options,
                results = LearnTTestResults$new(options = options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

#' T-Tests
#'
#' Learn about t-tests and compare group means.
#'
#' @param data the data as a data frame
#' @param testType the test type: \code{"independent"} (default),
#'   \code{"paired"}, or \code{"onesample"}
#' @param dep a string naming the dependent variable
#' @param group a string naming the grouping variable (independent t-test)
#' @param dep2 a string naming the second variable (paired t-test)
#' @param mu the null hypothesis mean (one-sample t-test, default 0)
#' @param hypothesis alternative hypothesis direction
#' @param showTheory \code{TRUE} (default) to show the theory section
#' @param showInstructions \code{TRUE} (default) to show Jamovi instructions
#' @return A results object containing t-test output
#' @examples
#' LearnTTest(data = ToothGrowth, testType = "independent",
#'            dep = "len", group = "supp")
#' @export
LearnTTest <- function(
    data,
    testType = 'independent',
    dep = NULL,
    group = NULL,
    dep2 = NULL,
    mu = 0,
    hypothesis = 'twoTailed',
    showTheory = TRUE,
    showInstructions = TRUE) {

    if (missing(data))
        data <- NULL

    options <- LearnTTestOptions$new(
        testType = testType,
        dep = dep,
        group = group,
        dep2 = dep2,
        mu = mu,
        hypothesis = hypothesis,
        showTheory = showTheory,
        showInstructions = showInstructions)

    analysis <- LearnTTestClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$results
}
