# This file is automatically generated, you probably don't want to edit this

LearnDescriptiveOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnDescriptiveOptions',
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            groupVar = NULL,
            showTheory = TRUE,
            showInstructions = TRUE,
            ...) {

            super$initialize(
                package = 'learnJamovi',
                name = 'LearnDescriptive',
                requiresData = TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                'vars', vars,
                suggested = list('continuous'),
                permitted = list('numeric'))

            private$..groupVar <- jmvcore::OptionVariable$new(
                'groupVar', groupVar,
                suggested = list('nominal', 'ordinal'),
                permitted = list('factor'))

            private$..showTheory <- jmvcore::OptionBool$new(
                'showTheory', showTheory)

            private$..showInstructions <- jmvcore::OptionBool$new(
                'showInstructions', showInstructions)

            self$.addOption(private$..vars)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..showTheory)
            self$.addOption(private$..showInstructions)
        }),
    active = list(
        vars = function() private$..vars$value,
        groupVar = function() private$..groupVar$value,
        showTheory = function() private$..showTheory$value,
        showInstructions = function() private$..showInstructions$value),
    private = list(
        ..vars = NA,
        ..groupVar = NA,
        ..showTheory = NA,
        ..showInstructions = NA))

LearnDescriptiveResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnDescriptiveResults',
    inherit = jmvcore::Group,
    active = list(
        theory = function() private$.items[['theory']],
        instructions = function() private$.items[['instructions']],
        descriptives = function() private$.items[['descriptives']]),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name = '',
                title = 'Descriptive Statistics')

            self$add(jmvcore::Html$new(
                options = options,
                name = 'theory',
                title = 'Statistical Theory',
                visible = '(showTheory)',
                clearWith = list()))

            self$add(jmvcore::Html$new(
                options = options,
                name = 'instructions',
                title = 'Jamovi Instructions',
                visible = '(showInstructions)',
                clearWith = list()))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'descriptives',
                title = 'Descriptive Statistics',
                rows = '(vars)',
                clearWith = list('vars', 'groupVar'),
                columns = list(
                    list(name = 'var',    title = 'Variable', type = 'text',    content = '($key)'),
                    list(name = 'n',      title = 'N',        type = 'integer'),
                    list(name = 'mean',   title = 'Mean',     type = 'number'),
                    list(name = 'median', title = 'Median',   type = 'number'),
                    list(name = 'sd',     title = 'SD',       type = 'number'),
                    list(name = 'se',     title = 'SE',       type = 'number'),
                    list(name = 'min',    title = 'Min',      type = 'number'),
                    list(name = 'max',    title = 'Max',      type = 'number'),
                    list(name = 'range',  title = 'Range',    type = 'number'),
                    list(name = 'skew',   title = 'Skewness', type = 'number'),
                    list(name = 'kurt',   title = 'Kurtosis', type = 'number'))))
        }))

LearnDescriptiveBase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnDescriptiveBase',
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = '', analysisId = '', revision = 0) {
            super$initialize(
                package = 'learnJamovi',
                name = 'LearnDescriptive',
                version = c(1, 0, 0),
                options = options,
                results = LearnDescriptiveResults$new(options = options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

#' Descriptive Statistics
#'
#' Learn about descriptive statistics and compute summary measures for
#' your continuous variables.
#'
#' @param data the data as a data frame
#' @param vars a vector of strings naming continuous variables in `data`
#' @param groupVar an optional grouping variable name
#' @param showTheory \code{TRUE} (default) to show the theory section
#' @param showInstructions \code{TRUE} (default) to show Jamovi instructions
#' @return A results object containing descriptive statistics
#' @examples
#' LearnDescriptive(data = iris, vars = c("Sepal.Length", "Sepal.Width"))
#' @export
LearnDescriptive <- function(
    data,
    vars = NULL,
    groupVar = NULL,
    showTheory = TRUE,
    showInstructions = TRUE) {

    if (missing(data))
        data <- NULL

    options <- LearnDescriptiveOptions$new(
        vars = vars,
        groupVar = groupVar,
        showTheory = showTheory,
        showInstructions = showInstructions)

    analysis <- LearnDescriptiveClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$results
}
