# This file is automatically generated, you probably don't want to edit this

LearnChiSquareOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnChiSquareOptions',
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            showTheory = TRUE,
            showInstructions = TRUE,
            ...) {

            super$initialize(
                package = 'learnJamovi',
                name = 'LearnChiSquare',
                requiresData = TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                'rows', rows,
                suggested = list('nominal', 'ordinal'),
                permitted = list('factor'))

            private$..cols <- jmvcore::OptionVariable$new(
                'cols', cols,
                suggested = list('nominal', 'ordinal'),
                permitted = list('factor'))

            private$..showTheory <- jmvcore::OptionBool$new(
                'showTheory', showTheory)

            private$..showInstructions <- jmvcore::OptionBool$new(
                'showInstructions', showInstructions)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..showTheory)
            self$.addOption(private$..showInstructions)
        }),
    active = list(
        rows             = function() private$..rows$value,
        cols             = function() private$..cols$value,
        showTheory       = function() private$..showTheory$value,
        showInstructions = function() private$..showInstructions$value),
    private = list(
        ..rows             = NA,
        ..cols             = NA,
        ..showTheory       = NA,
        ..showInstructions = NA))

LearnChiSquareResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnChiSquareResults',
    inherit = jmvcore::Group,
    active = list(
        theory       = function() private$.items[['theory']],
        instructions = function() private$.items[['instructions']],
        chiSq        = function() private$.items[['chiSq']],
        freq         = function() private$.items[['freq']]),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name = '',
                title = 'Chi-Square Tests')

            self$add(jmvcore::Html$new(
                options = options,
                name = 'theory',
                title = 'Statistical Theory',
                visible = '(showTheory)',
                clearWith = list()))

            self$add(jmvcore::Html$new(
                options = options,
                name = 'instructions',
                title = 'Jamovi Instructions',
                visible = '(showInstructions)',
                clearWith = list()))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'chiSq',
                title = 'Chi-Square Test of Independence',
                clearWith = list('rows', 'cols'),
                columns = list(
                    list(name = 'test',     title = 'Test',       type = 'text'),
                    list(name = 'value',    title = '\u03c7\u00b2', type = 'number'),
                    list(name = 'df',       title = 'df',         type = 'integer'),
                    list(name = 'p',        title = 'p',          type = 'number', format = 'zto,pvalue'),
                    list(name = 'cramersV', title = 'Cram\u00e9r\'s V', type = 'number', format = 'zto'))))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'freq',
                title = 'Observed Counts',
                clearWith = list('rows', 'cols'),
                columns = list(
                    list(name = 'rowLabel', title = '', type = 'text'),
                    list(name = 'counts',   title = 'Counts', type = 'text'))))
        }))

LearnChiSquareBase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnChiSquareBase',
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = '', analysisId = '', revision = 0) {
            super$initialize(
                package = 'learnJamovi',
                name = 'LearnChiSquare',
                version = c(1, 0, 0),
                options = options,
                results = LearnChiSquareResults$new(options = options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

#' Chi-Square Tests
#'
#' Learn chi-square tests for categorical data.
#'
#' @param data the data as a data frame
#' @param rows a string naming the row categorical variable
#' @param cols a string naming the column categorical variable
#' @param showTheory \code{TRUE} (default) to show the theory section
#' @param showInstructions \code{TRUE} (default) to show Jamovi instructions
#' @return A results object containing chi-square test output
#' @examples
#' df <- as.data.frame(UCBAdmissions)
#' LearnChiSquare(data = df, rows = "Admit", cols = "Gender")
#' @export
LearnChiSquare <- function(
    data,
    rows = NULL,
    cols = NULL,
    showTheory = TRUE,
    showInstructions = TRUE) {

    if (missing(data))
        data <- NULL

    options <- LearnChiSquareOptions$new(
        rows = rows,
        cols = cols,
        showTheory = showTheory,
        showInstructions = showInstructions)

    analysis <- LearnChiSquareClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$results
}
