# This file is automatically generated, you probably don't want to edit this

LearnRegressionOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnRegressionOptions',
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            showTheory = TRUE,
            showInstructions = TRUE,
            ...) {

            super$initialize(
                package = 'learnJamovi',
                name = 'LearnRegression',
                requiresData = TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                'dep', dep,
                suggested = list('continuous'),
                permitted = list('numeric'))

            private$..covs <- jmvcore::OptionVariables$new(
                'covs', covs,
                suggested = list('continuous'),
                permitted = list('numeric', 'factor'))

            private$..showTheory <- jmvcore::OptionBool$new(
                'showTheory', showTheory)

            private$..showInstructions <- jmvcore::OptionBool$new(
                'showInstructions', showInstructions)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..showTheory)
            self$.addOption(private$..showInstructions)
        }),
    active = list(
        dep              = function() private$..dep$value,
        covs             = function() private$..covs$value,
        showTheory       = function() private$..showTheory$value,
        showInstructions = function() private$..showInstructions$value),
    private = list(
        ..dep              = NA,
        ..covs             = NA,
        ..showTheory       = NA,
        ..showInstructions = NA))

LearnRegressionResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnRegressionResults',
    inherit = jmvcore::Group,
    active = list(
        theory       = function() private$.items[['theory']],
        instructions = function() private$.items[['instructions']],
        modelFit     = function() private$.items[['modelFit']],
        coeff        = function() private$.items[['coeff']]),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name = '',
                title = 'Linear Regression')

            self$add(jmvcore::Html$new(
                options = options,
                name = 'theory',
                title = 'Statistical Theory',
                visible = '(showTheory)',
                clearWith = list()))

            self$add(jmvcore::Html$new(
                options = options,
                name = 'instructions',
                title = 'Jamovi Instructions',
                visible = '(showInstructions)',
                clearWith = list()))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'modelFit',
                title = 'Model Fit',
                clearWith = list('dep', 'covs'),
                columns = list(
                    list(name = 'r',     title = 'R',            type = 'number'),
                    list(name = 'r2',    title = 'R\u00b2',      type = 'number', format = 'zto'),
                    list(name = 'r2adj', title = 'Adj. R\u00b2', type = 'number', format = 'zto'),
                    list(name = 'f',     title = 'F',            type = 'number'),
                    list(name = 'df1',   title = 'df1',          type = 'integer'),
                    list(name = 'df2',   title = 'df2',          type = 'integer'),
                    list(name = 'p',     title = 'p',            type = 'number', format = 'zto,pvalue'))))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'coeff',
                title = 'Coefficients',
                clearWith = list('dep', 'covs'),
                columns = list(
                    list(name = 'term',    title = 'Predictor',   type = 'text'),
                    list(name = 'b',       title = 'b',           type = 'number'),
                    list(name = 'se',      title = 'SE',          type = 'number'),
                    list(name = 'beta',    title = '\u03b2 (std.)', type = 'number'),
                    list(name = 't',       title = 't',           type = 'number'),
                    list(name = 'p',       title = 'p',           type = 'number', format = 'zto,pvalue'),
                    list(name = 'cilower', title = 'Lower',       type = 'number', superTitle = '95% CI'),
                    list(name = 'ciupper', title = 'Upper',       type = 'number', superTitle = '95% CI'))))
        }))

LearnRegressionBase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnRegressionBase',
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = '', analysisId = '', revision = 0) {
            super$initialize(
                package = 'learnJamovi',
                name = 'LearnRegression',
                version = c(1, 0, 0),
                options = options,
                results = LearnRegressionResults$new(options = options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

#' Linear Regression
#'
#' Learn about linear regression and predict a continuous outcome.
#'
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable
#' @param covs a vector of strings naming the predictor variables
#' @param showTheory \code{TRUE} (default) to show the theory section
#' @param showInstructions \code{TRUE} (default) to show Jamovi instructions
#' @return A results object containing model fit and coefficients
#' @examples
#' LearnRegression(data = mtcars, dep = "mpg", covs = c("hp", "wt"))
#' @export
LearnRegression <- function(
    data,
    dep = NULL,
    covs = NULL,
    showTheory = TRUE,
    showInstructions = TRUE) {

    if (missing(data))
        data <- NULL

    options <- LearnRegressionOptions$new(
        dep = dep,
        covs = covs,
        showTheory = showTheory,
        showInstructions = showInstructions)

    analysis <- LearnRegressionClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$results
}
