# This file is automatically generated, you probably don't want to edit this

LearnANOVAOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnANOVAOptions',
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            factor = NULL,
            postHoc = FALSE,
            showTheory = TRUE,
            showInstructions = TRUE,
            ...) {

            super$initialize(
                package = 'learnJamovi',
                name = 'LearnANOVA',
                requiresData = TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                'dep', dep,
                suggested = list('continuous'),
                permitted = list('numeric'))

            private$..factor <- jmvcore::OptionVariable$new(
                'factor', factor,
                suggested = list('nominal', 'ordinal'),
                permitted = list('factor'))

            private$..postHoc <- jmvcore::OptionBool$new(
                'postHoc', postHoc)

            private$..showTheory <- jmvcore::OptionBool$new(
                'showTheory', showTheory)

            private$..showInstructions <- jmvcore::OptionBool$new(
                'showInstructions', showInstructions)

            self$.addOption(private$..dep)
            self$.addOption(private$..factor)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..showTheory)
            self$.addOption(private$..showInstructions)
        }),
    active = list(
        dep              = function() private$..dep$value,
        factor           = function() private$..factor$value,
        postHoc          = function() private$..postHoc$value,
        showTheory       = function() private$..showTheory$value,
        showInstructions = function() private$..showInstructions$value),
    private = list(
        ..dep              = NA,
        ..factor           = NA,
        ..postHoc          = NA,
        ..showTheory       = NA,
        ..showInstructions = NA))

LearnANOVAResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnANOVAResults',
    inherit = jmvcore::Group,
    active = list(
        theory       = function() private$.items[['theory']],
        instructions = function() private$.items[['instructions']],
        anova        = function() private$.items[['anova']],
        desc         = function() private$.items[['desc']],
        postHocTable = function() private$.items[['postHocTable']]),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name = '',
                title = 'One-Way ANOVA')

            self$add(jmvcore::Html$new(
                options = options,
                name = 'theory',
                title = 'Statistical Theory',
                visible = '(showTheory)',
                clearWith = list()))

            self$add(jmvcore::Html$new(
                options = options,
                name = 'instructions',
                title = 'Jamovi Instructions',
                visible = '(showInstructions)',
                clearWith = list()))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'anova',
                title = 'ANOVA',
                clearWith = list('dep', 'factor'),
                columns = list(
                    list(name = 'source', title = 'Source',          type = 'text'),
                    list(name = 'ss',     title = 'Sum of Squares',  type = 'number'),
                    list(name = 'df',     title = 'df',              type = 'integer'),
                    list(name = 'ms',     title = 'Mean Square',     type = 'number'),
                    list(name = 'f',      title = 'F',               type = 'number'),
                    list(name = 'p',      title = 'p',               type = 'number', format = 'zto,pvalue'),
                    list(name = 'etaSq',  title = '\u03b7\u00b2',    type = 'number', format = 'zto'))))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'desc',
                title = 'Group Descriptives',
                clearWith = list('dep', 'factor'),
                columns = list(
                    list(name = 'group', title = 'Group', type = 'text'),
                    list(name = 'n',     title = 'N',     type = 'integer'),
                    list(name = 'mean',  title = 'Mean',  type = 'number'),
                    list(name = 'sd',    title = 'SD',    type = 'number'),
                    list(name = 'se',    title = 'SE',    type = 'number'))))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'postHocTable',
                title = 'Post-Hoc Comparisons (Tukey HSD)',
                visible = '(postHoc)',
                clearWith = list('dep', 'factor', 'postHoc'),
                columns = list(
                    list(name = 'comparison', title = 'Comparison',     type = 'text'),
                    list(name = 'md',         title = 'Mean diff.',     type = 'number'),
                    list(name = 'cilower',    title = 'Lower',          type = 'number', superTitle = '95% Tukey CI'),
                    list(name = 'ciupper',    title = 'Upper',          type = 'number', superTitle = '95% Tukey CI'),
                    list(name = 'pTukey',     title = 'p (Tukey)',      type = 'number', format = 'zto,pvalue'))))
        }))

LearnANOVABase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnANOVABase',
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = '', analysisId = '', revision = 0) {
            super$initialize(
                package = 'learnJamovi',
                name = 'LearnANOVA',
                version = c(1, 0, 0),
                options = options,
                results = LearnANOVAResults$new(options = options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

#' One-Way ANOVA
#'
#' Learn about one-way ANOVA and compare group means.
#'
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable
#' @param factor a string naming the grouping factor
#' @param postHoc \code{TRUE} to compute Tukey HSD post-hoc comparisons
#' @param showTheory \code{TRUE} (default) to show the theory section
#' @param showInstructions \code{TRUE} (default) to show Jamovi instructions
#' @return A results object containing ANOVA output
#' @examples
#' LearnANOVA(data = iris, dep = "Sepal.Length", factor = "Species")
#' @export
LearnANOVA <- function(
    data,
    dep = NULL,
    factor = NULL,
    postHoc = FALSE,
    showTheory = TRUE,
    showInstructions = TRUE) {

    if (missing(data))
        data <- NULL

    options <- LearnANOVAOptions$new(
        dep = dep,
        factor = factor,
        postHoc = postHoc,
        showTheory = showTheory,
        showInstructions = showInstructions)

    analysis <- LearnANOVAClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$results
}
