# This file is automatically generated, you probably don't want to edit this

LearnCorrelationOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnCorrelationOptions',
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            method = 'pearson',
            flagSig = TRUE,
            showTheory = TRUE,
            showInstructions = TRUE,
            ...) {

            super$initialize(
                package = 'learnJamovi',
                name = 'LearnCorrelation',
                requiresData = TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                'vars', vars,
                suggested = list('continuous'),
                permitted = list('numeric'))

            private$..method <- jmvcore::OptionList$new(
                'method', method,
                options = list('pearson', 'spearman', 'kendall'))

            private$..flagSig <- jmvcore::OptionBool$new(
                'flagSig', flagSig)

            private$..showTheory <- jmvcore::OptionBool$new(
                'showTheory', showTheory)

            private$..showInstructions <- jmvcore::OptionBool$new(
                'showInstructions', showInstructions)

            self$.addOption(private$..vars)
            self$.addOption(private$..method)
            self$.addOption(private$..flagSig)
            self$.addOption(private$..showTheory)
            self$.addOption(private$..showInstructions)
        }),
    active = list(
        vars             = function() private$..vars$value,
        method           = function() private$..method$value,
        flagSig          = function() private$..flagSig$value,
        showTheory       = function() private$..showTheory$value,
        showInstructions = function() private$..showInstructions$value),
    private = list(
        ..vars             = NA,
        ..method           = NA,
        ..flagSig          = NA,
        ..showTheory       = NA,
        ..showInstructions = NA))

LearnCorrelationResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnCorrelationResults',
    inherit = jmvcore::Group,
    active = list(
        theory       = function() private$.items[['theory']],
        instructions = function() private$.items[['instructions']],
        matrix       = function() private$.items[['matrix']]),
    public = list(
        initialize = function(options) {
            super$initialize(
                options = options,
                name = '',
                title = 'Correlation')

            self$add(jmvcore::Html$new(
                options = options,
                name = 'theory',
                title = 'Statistical Theory',
                visible = '(showTheory)',
                clearWith = list()))

            self$add(jmvcore::Html$new(
                options = options,
                name = 'instructions',
                title = 'Jamovi Instructions',
                visible = '(showInstructions)',
                clearWith = list()))

            self$add(jmvcore::Table$new(
                options = options,
                name = 'matrix',
                title = 'Correlation Matrix',
                clearWith = list('vars', 'method', 'flagSig'),
                columns = list(
                    list(name = 'v1',      title = 'Variable 1', type = 'text'),
                    list(name = 'v2',      title = 'Variable 2', type = 'text'),
                    list(name = 'r',       title = 'r',          type = 'number'),
                    list(name = 'p',       title = 'p',          type = 'number', format = 'zto,pvalue'),
                    list(name = 'n',       title = 'N',          type = 'integer'),
                    list(name = 'cilower', title = 'Lower',      type = 'number', superTitle = '95% CI'),
                    list(name = 'ciupper', title = 'Upper',      type = 'number', superTitle = '95% CI'))))
        }))

LearnCorrelationBase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    'LearnCorrelationBase',
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = '', analysisId = '', revision = 0) {
            super$initialize(
                package = 'learnJamovi',
                name = 'LearnCorrelation',
                version = c(1, 0, 0),
                options = options,
                results = LearnCorrelationResults$new(options = options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

#' Correlation
#'
#' Learn about correlation and explore relationships between continuous variables.
#'
#' @param data the data as a data frame
#' @param vars a vector of strings naming the variables to correlate
#' @param method the correlation method: \code{"pearson"} (default),
#'   \code{"spearman"}, or \code{"kendall"}
#' @param flagSig \code{TRUE} (default) to flag significant correlations
#' @param showTheory \code{TRUE} (default) to show the theory section
#' @param showInstructions \code{TRUE} (default) to show Jamovi instructions
#' @return A results object containing the correlation matrix
#' @examples
#' LearnCorrelation(data = iris,
#'     vars = c("Sepal.Length", "Sepal.Width", "Petal.Length"))
#' @export
LearnCorrelation <- function(
    data,
    vars = NULL,
    method = 'pearson',
    flagSig = TRUE,
    showTheory = TRUE,
    showInstructions = TRUE) {

    if (missing(data))
        data <- NULL

    options <- LearnCorrelationOptions$new(
        vars = vars,
        method = method,
        flagSig = flagSig,
        showTheory = showTheory,
        showInstructions = showInstructions)

    analysis <- LearnCorrelationClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$results
}
